import type {Event} from '../../src/types/elements-pages'
export const allevents: Event[] = [
    {
        id: 1,
        idDueño: 2,
        titulo: "Cuentacuentos e ilustracion",
        startDate: "02/02/2023",
        endDate: "03/04/2024",
        description: "Evento ficticio de prueba numero 1 para mostrar en la pagina. El panfleto se tomo al azar de internet y los datos no tienen relacion",
        mainImage: '/Recursos simulados/File Container/as-panfleto.jpg',
        disponible: true,
        estado: "habilitado",
    },
    {
        id: 2,
        idDueño: 2,
        titulo: "Curso para psicos...",
        startDate: "02/02/2003",
        endDate: "04/05/2027",
        description: "Evento ficticio de prueba numero 2 para mostrar en la pagina. El panfleto se tomo al azar de internet y los datos no tienen relacion",
        mainImage: '/Recursos simulados/File Container/as-panfleto2.jpg',
        disponible: false,
        estado: "habilitado",
    },
    {
        id: 3,
        idDueño: 3,
        titulo: "Curso de Cuidadores",
        startDate: "03/03/2003",
        endDate: "05/05/2027",
        description: "Evento ficticio de prueba numero 3 para mostrar en la pagina. El panfleto se tomo al azar de internet y los datos no tienen relacion",
        mainImage: '/Recursos simulados/File Container/as-panfleto4.jpg',
        disponible: true,
        estado: "en espera",
    },
    {
        id: 4,
        idDueño: 4,
        titulo: "La importancia de la Supervision",
        startDate: "04/04/2003",
        endDate: "04/06/2027",
        description: "Evento ficticio de prueba numero 4 para mostrar en la pagina. El panfleto se tomo al azar de internet y los datos no tienen relacion",
        mainImage: '/Recursos simulados/File Container/as-panfleto5.jpg',
        disponible: true,
        estado: "habilitado",
    },
    {
        id: 5,
        idDueño: 5,
        titulo: "Sueroterapia avanzada",
        startDate: "15/15/2003",
        endDate: "1/1/2027",
        description: "Evento ficticio de prueba numero 5 para mostrar en la pagina. El panfleto se tomo al azar de internet y los datos no tienen relacion",
        mainImage: '/Recursos simulados/File Container/as-panfleto6.jpg',
        disponible: true,
        estado: "habilitado",
    },
    {
        id: 6,
        idDueño: 6,
        titulo: "Psicosamatica del cuerpo",
        startDate: "16/16/2003",
        endDate: "1/1/2027",
        description: "Evento ficticio de prueba numero 6 para mostrar en la pagina. El panfleto se tomo al azar de internet y los datos no tienen relacion",
        mainImage: '/Recursos simulados/File Container/as-panfleto7.webp',
        disponible: true,
        estado: "habilitado",
    },
    {
        id: 7,
        idDueño: 7,
        titulo: "Taller online",
        startDate: "17/17/2003",
        endDate: "1/1/2027",
        description: "Evento de prueba numero 7 Evento de prueba numero 1 Evento de prueba numero 7 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 ",
        mainImage: '/Recursos simulados/File Container/as-panfleto8.jpg',
        disponible: true,
        estado: "habilitado",
    },
    {
        id: 8,
        idDueño: 8,
        titulo: "Taller de sonidos",
        startDate: "18/18/2003",
        endDate: "1/1/2027",
        description: "Evento ficticio de prueba numero 8 para mostrar en la pagina. El panfleto se tomo al azar de internet y los datos no tienen relacion",
        mainImage: '/Recursos simulados/File Container/as-panfleto9.jpg',
        disponible: false,
        estado: "habilitado",
    },
    {
        id: 9,
        idDueño: 9,
        titulo: "Nombre de Evento",
        startDate: "19/19/2003",
        endDate: "1/1/2027",
        description: "Evento ficticio de prueba numero 9 para mostrar en la pagina. El panfleto se tomo al azar de internet y los datos no tienen relacion",
        mainImage: '/Recursos simulados/File Container/titulo.jpg',
        disponible: true,
        estado: "habilitado",
    }
]