import type {User} from '../../src/types/elements-pages'
export const allusers: User[] = [
    {
        id: 1,
        nombre: "Juan Ignacion Rodriguez",
        password:"12345678",
        email: "nacho@gmail.com",
        phone: "12345678910",
        disponible: true,
        estado: "habilitado",
        rangoEtareo: ["Niñx"],
        profileImage: "/Recursos simulados/File Container/user1.png",
        mainImage: "/Recursos simulados/File Container/titulo.jpg",
        rol: "admin",
        esSupervisor: false,
        titulo: "Acompañante terapéutico"
    },
    {
        id: 2,
        nombre: "Hernan Hernandez",
        password:"12345678",
        email: "hernan@gmail.com",
        phone: "12345678910",
        disponible: true,
        estado: "habilitado",
        rangoEtareo: ["Niñx"],
        profileImage: "/Recursos simulados/File Container/user2.png",
        mainImage: "/Recursos simulados/File Container/titulo.jpg",
        rol: "profesional",
        titulo: "Licenciadx",
        esSupervisor: true
    },
    {
        id: 3,
        nombre: "Gonzalo Gonzalez",
        password:"12345678",
        email: "gonzalo@gmail.com",
        phone: "12345678910",
        disponible: false,
        estado: "habilitado",
        rangoEtareo: ["Niñx"],
        profileImage: "/Recursos simulados/File Container/user3.webp",
        mainImage: "/Recursos simulados/File Container/titulo.jpg",
        rol: "profesional",
        esSupervisor: false,
        titulo: "Tecnicx"
    },
    {
        id: 4,
        nombre: "Martina Martinez",
        password:"12345678",
        email: "martina@gmail.com",
        phone: "12345678910",
        disponible: true,
        estado: "habilitado",
        rangoEtareo: ["Niñx"],
        profileImage: "/Recursos simulados/File Container/user4.png",
        mainImage: "/Recursos simulados/File Container/titulo.jpg",
        rol: "profesional",
        esSupervisor: false,
        titulo: "Tecnicx Superior"
    },
    {
        id: 5,
        nombre: "Fernanda Fernandez",
        password:"12345678",
        email: "fernanda@gmail.com",
        phone: "12345678910",
        disponible: true,
        estado: "habilitado",
        rangoEtareo: ["Niñx"],
        profileImage: "/Recursos simulados/File Container/user5.png",
        mainImage: "/Recursos simulados/File Container/titulo.jpg",
        rol: "profesional",
        esSupervisor: false,
        titulo: "Acompañante terapéutico"
    },
    {
        id: 6,
        nombre: "Juan Juarez",
        password:"12345678",
        email: "juan@gmail.com",
        phone: "12345678910",
        disponible: true,
        estado: "habilitado",
        rangoEtareo: ["Niñx"],
        profileImage: "/Recursos simulados/File Container/user6.jpeg",
        mainImage: "/Recursos simulados/File Container/titulo.jpg",
        rol: "profesional",
        esSupervisor: false,
        titulo: "Licenciadx"
    },
    {
        id: 7,
        nombre: "Esteban Estebanez",
        password:"12345678",
        email: "esteban2@gmail.com",
        phone: "12345678910",
        disponible: true,
        estado: "habilitado",
        rangoEtareo: ["Niñx"],
        profileImage: "/Recursos simulados/File Container/user7.png",
        mainImage: "/Recursos simulados/File Container/titulo.jpg",
        rol: "profesional",
        esSupervisor: false,
        titulo: "Tecnicx"
    },
    {
        id: 8,
        nombre: "Ivan Ivañez",
        password:"12345678",
        email: "ivan@gmail.com",
        phone: "12345678910",
        disponible: true,
        estado: "habilitado",
        rangoEtareo: ["Niñx"],
        profileImage: "/Recursos simulados/File Container/user8.png",
        mainImage: "/Recursos simulados/File Container/titulo.jpg",
        rol: "profesional",
        esSupervisor: false,
        titulo: "Tecnicx Superior"
    },
    {
        id: 11,
        nombre: "Juan Ignacion Rodriguez",
        password:"12345678",
        email: "nacho2@gmail.com",
        phone: "12345678910",
        disponible: false,
        estado: "en espera",
        rangoEtareo: undefined,
        profileImage: undefined,
        mainImage: undefined,
        rol: "usuario"
    },
    {
        id: 12,
        nombre: "Hernan Hernandez",
        password:"12345678",
        email: "hernan2@gmail.com",
        phone: "12345678910",
        disponible: false,
        estado: "en espera",
        rangoEtareo: undefined,
        profileImage: undefined,
        mainImage: undefined,
        rol: "usuario"
    },
    {
        id: 13,
        nombre: "Gonzalo Gonzalez",
        password:"12345678",
        email: "gonzalo2@gmail.com",
        phone: "12345678910",
        disponible: false,
        estado: "en espera",
        rangoEtareo: undefined,
        profileImage: undefined,
        mainImage: undefined,
        rol: "usuario"
    },
    {
        id: 14,
        nombre: "Martina Martinez",
        password:"12345678",
        email: "martina2@gmail.com",
        phone: "12345678910",
        disponible: false,
        estado: "en espera",
        rangoEtareo: undefined,
        profileImage: undefined,
        mainImage: undefined,
        rol: "usuario"
    },
    {
        id: 15,
        nombre: "Fernanda Fernandez",
        password:"12345678",
        email: "fernanda2@gmail.com",
        phone: "12345678910",
        disponible: false,
        estado: "en espera",
        rangoEtareo: undefined,
        profileImage: undefined,
        mainImage: undefined,
        rol: "usuario"
    },
    {
        id: 16,
        nombre: "Juan Juarez",
        password:"12345678",
        email: "juan2@gmail.com",
        phone: "12345678910",
        disponible: false,
        estado: "en espera",
        rangoEtareo: undefined,
        profileImage: undefined,
        mainImage: undefined,
        rol: "usuario"
    },
    {
        id: 17,
        nombre: "Esteban Estebanez",
        password:"12345678",
        email: "esteban2@gmail.com",
        phone: "12345678910",
        disponible: false,
        estado: "en espera",
        rangoEtareo: undefined,
        profileImage: undefined,
        mainImage: undefined,
        rol: "usuario"
    },
    {
        id: 18,
        nombre: "Ivan Ivañez",
        password:"12345678",
        email: "ivan2@gmail.com",
        phone: "12345678910",
        disponible: false,
        estado: "habilitado",
        rangoEtareo: undefined,
        profileImage: undefined,
        mainImage: undefined,
        rol: "usuario"
    }
]