import type {Case} from '../src/types/elements-pages'
export const allcases: Case[]  = [
    {
        id: 1,
        idDueño: 1,
        estado: "habilitado",
        disponible: true,
        tipoPaciente: "Niñx",
        dx: "TDH",
        edad: 12,
        contacto:["juan@hotmail.com","223678921"],
        solicitud: "Se busca un acompañante terapéutico (varon excluyente) para un turno de mañana",
        covertura: "PARTICULAR - 123456 x hora",
        franjahoraria: "08 a 12",
        
    },
    {
        id: 2,
        idDueño: 1,
        estado: "habilitado",
        disponible: true,
        tipoPaciente: "Adolecente",
        dx: "TDH",
        edad: 24,
        contacto:["juan@hotmail.com","223678921"],
        solicitud: "Se busca un acompañante terapéutico (varon excluyente) para un turno de mañana",
        covertura: "OSDEPYM - ",
        franjahoraria: "08 a 12"
        
    },
    {
        id: 3,
        idDueño: 1,
        estado: "habilitado",
        disponible: true,
        tipoPaciente: "Adulto",
        dx: "TDH",
        edad: 36,
        contacto:["juan@hotmail.com","223678921"],
        solicitud: "Se busca un acompañante terapéutico (varon excluyente) para un turno de mañana",
        covertura: "PARTICULAR - 123456 x hora",
        franjahoraria: "08 a 12"
    },    
    {
        id: 4,
        idDueño: 1,
        estado: "en espera",
        disponible: true,
        tipoPaciente: "Adulto mayor",
        dx: "TDH",
        edad: 72,
        contacto:["juan@hotmail.com","223678921"],
        solicitud: "Se busca un acompañante terapéutico (varon excluyente) para un turno de mañana",
        covertura: "PARTICULAR - 123456 x hora",
        franjahoraria: "08 a 12"
    }    ,
    {
        id: 5,
        idDueño: 1,
        estado: "rechazado",
        disponible: true,
        tipoPaciente: "Adolecente",
        dx: "TDH",
        edad: 24,
        contacto:["juan@hotmail.com","223678921"],
        solicitud: "Se busca un acompañante terapéutico (varon excluyente) para un turno de mañana",
        covertura: "OSDEPYM - ",
        franjahoraria: "08 a 12"
        
    },
    {
        id: 6,
        idDueño: 1,
        estado: "habilitado",
        disponible: true,
        tipoPaciente: "Adulto",
        dx: "TDH",
        edad: 36,
        contacto:["juan@hotmail.com","223678921"],
        solicitud: "Se busca un acompañante terapéutico (varon excluyente) para un turno de mañana",
        covertura: "PARTICULAR - 123456 x hora",
        franjahoraria: "08 a 12"
    },    
    {
        id: 7,
        idDueño: 1,
        estado: "habilitado",
        disponible: true,
        tipoPaciente: "Adulto mayor",
        dx: "TDH",
        edad: 72,
        contacto:["juan@hotmail.com","223678921"],
        solicitud: "Se busca un acompañante terapéutico (varon excluyente) para un turno de mañana",
        covertura: "PARTICULAR - 123456 x hora",
        franjahoraria: "08 a 12"
    }    ,
    {
        id: 8,
        idDueño: 1,
        estado: "en espera",
        disponible: true,
        tipoPaciente: "Adolecente",
        dx: "TDH",
        edad: 24,
        contacto:["juan@hotmail.com","223678921"],
        solicitud: "Se busca un acompañante terapéutico (varon excluyente) para un turno de mañana",
        covertura: "OSDEPYM - ",
        franjahoraria: "08 a 12"
        
    },
    {
        id: 9,
        idDueño: 1,
        estado: "habilitado",
        disponible: true,
        tipoPaciente: "Adulto",
        dx: "TDH",
        edad: 36,
        contacto:["juan@hotmail.com","223678921"],
        solicitud: "Se busca un acompañante terapéutico (varon excluyente) para un turno de mañana",
        covertura: "PARTICULAR - 123456 x hora",
        franjahoraria: "08 a 12"
    },    
    {
        id: 10,
        idDueño: 1,
        estado: "habilitado",
        disponible: true,
        tipoPaciente: "Adulto mayor",
        dx: "TDH",
        edad: 72,
        contacto:["juan@hotmail.com","223678921"],
        solicitud: "Se busca un acompañante terapéutico (varon excluyente) para un turno de mañana",
        covertura: "PARTICULAR - 123456 x hora",
        franjahoraria: "08 a 12"
    }    ,
    {
        id: 11,
        idDueño: 1,
        estado: "habilitado",
        disponible: true,
        tipoPaciente: "Adolecente",
        dx: "TDH",
        edad: 24,
        contacto:["juan@hotmail.com","223678921"],
        solicitud: "Se busca un acompañante terapéutico (varon excluyente) para un turno de mañana",
        covertura: "OSDEPYM - ",
        franjahoraria: "08 a 12"
        
    },
    {
        id: 12,
        idDueño: 1,
        estado: "en espera",
        disponible: true,
        tipoPaciente: "Adulto",
        dx: "TDH",
        edad: 36,
        contacto:["juan@hotmail.com","223678921"],
        solicitud: "Se busca un acompañante terapéutico (varon excluyente) para un turno de mañana",
        covertura: "PARTICULAR - 123456 x hora",
        franjahoraria: "08 a 12"
    },    
    {
        id: 13,
        idDueño: 1,
        estado: "habilitado",
        disponible: true,
        tipoPaciente: "Adulto mayor",
        dx: "TDH",
        edad: 72,
        contacto:["juan@hotmail.com","223678921"],
        solicitud: "Se busca un acompañante terapéutico (varon excluyente) para un turno de mañana",
        covertura: "PARTICULAR - 123456 x hora",
        franjahoraria: "08 a 12"
    }    ,
    {
        id: 14,
        idDueño: 1,
        estado: "habilitado",
        disponible: true,
        tipoPaciente: "Adolecente",
        dx: "TDH",
        edad: 24,
        contacto:["juan@hotmail.com","223678921"],
        solicitud: "Se busca un acompañante terapéutico (varon excluyente) para un turno de mañana",
        covertura: "OSDEPYM - ",
        franjahoraria: "08 a 12"
        
    },
    {
        id: 15,
        idDueño: 1,
        estado: "rechazado",
        disponible: true,
        tipoPaciente: "Adulto",
        dx: "TDH",
        edad: 36,
        contacto:["juan@hotmail.com","223678921"],
        solicitud: "Se busca un acompañante terapéutico (varon excluyente) para un turno de mañana",
        covertura: "PARTICULAR - 123456 x hora",
        franjahoraria: "08 a 12"
    }
]
