import type {Event} from '../src/types/elements-pages'
export const allevents: Event[] = [
    {
        id: 1,
        idDueño: 2,
        titulo: "Nombre de Evento",
        startDate: "12/12/2003",
        endDate: "1/1/2004",
        description: "Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 ",
        mainImage: '/Recursos simulados/File Container/titulo.jpg',
        disponible: true,
        estado: "habilitado",
    },
    {
        id: 2,
        idDueño: 2,
        titulo: "Nombre de Evento",
        startDate: "1/11/2003",
        endDate: "2/12/2003",
        description: "Evento de prueba numero 2 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 ",
        mainImage: '/Recursos simulados/File Container/titulo.jpg',
        disponible: true,
        estado: "en espera",
    },
    {
        id: 3,
        idDueño: 3,
        titulo: "Nombre de Evento",
        startDate: "12/12/2003",
        endDate: "1/1/2004",
        description: "Evento de prueba numero 3 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 ",
        mainImage: '/Recursos simulados/File Container/titulo.jpg',
        disponible: true,
        estado: "en espera",
    },
    {
        id: 4,
        idDueño: 4,
        titulo: "Nombre de Evento",
        startDate: "12/12/2003",
        endDate: "1/1/2004",
        description: "Evento de prueba numero 4 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 ",
        mainImage: '/Recursos simulados/File Container/titulo.jpg',
        disponible: true,
        estado: "habilitado",
    },
    {
        id: 5,
        idDueño: 5,
        titulo: "Nombre de Evento",
        startDate: "12/12/2003",
        endDate: "1/1/2004",
        description: "Evento de prueba numero 5 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 ",
        mainImage: '/Recursos simulados/File Container/titulo.jpg',
        disponible: true,
        estado: "en espera",
    },
    {
        id: 6,
        idDueño: 6,
        titulo: "Nombre de Evento",
        startDate: "12/12/2003",
        endDate: "1/1/2004",
        description: "Evento de prueba numero 6 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 ",
        mainImage: '/Recursos simulados/File Container/titulo.jpg',
        disponible: true,
        estado: "rechazado",
    },
    {
        id: 7,
        idDueño: 7,
        titulo: "Nombre de Evento",
        startDate: "12/12/2003",
        endDate: "1/1/2004",
        description: "Evento de prueba numero 7 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 ",
        mainImage: '/Recursos simulados/File Container/titulo.jpg',
        disponible: true,
        estado: "rechazado",
    },
    {
        id: 8,
        idDueño: 8,
        titulo: "Nombre de Evento",
        startDate: "12/12/2003",
        endDate: "1/1/2004",
        description: "Evento de prueba numero 8 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 ",
        mainImage: '/Recursos simulados/File Container/titulo.jpg',
        disponible: true,
        estado: "habilitado",
    },
    {
        id: 9,
        idDueño: 9,
        titulo: "Nombre de Evento",
        startDate: "12/12/2003",
        endDate: "1/1/2004",
        description: "Evento de prueba numero 9 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 Evento de prueba numero 1 ",
        mainImage: '/Recursos simulados/File Container/titulo.jpg',
        disponible: true,
        estado: "en espera",
    }
]